### ISSUE TITLE
Syntax error in alpr.rb

### ISSUE THREAD

**Issue by xcodewarrier** [twelve17/openalpr-ios#11]
On running **bundle exec ./bin/build_frameworks.rb** on El Capitan as per the readme, the script fails with a syntax error as follows:

    $ bundle exec ./bin/build_frameworks.rb
    /Users/username/dev/iOS/openalpr-ios/lib/alpr/package.rb:1:in `require_relative':      /Users/username/dev/iOS/openalpr-ios/lib/alpr/package/alpr.rb:31: syntax error, unexpected ',' (SyntaxError)
    def initialize(log_file:, logger:,
                             ^
    /Users/username/dev/iOS/openalpr-ios/lib/alpr/package/alpr.rb:173: syntax error, unexpected keyword_end, expecting end-of-input
	from /Users/username/dev/iOS/openalpr-ios/lib/alpr/package.rb:1:in `<top (required)>'
	from ./bin/build_frameworks.rb:7:in `require_relative'
	from ./bin/build_frameworks.rb:7:in `<main>'

**Comment by twelve17** [comment]
Are you on Ruby 2.1.2+?

**Comment by xcodewarrier** [comment]
Verified that this was issue - I was on Ruby 2.0.
