### ISSUE TITLE
Specify parameters, e.g. country 

### ISSUE THREAD

**Issue by xcodewarrier** [twelve17/openalpr-ios#12]
There should be a mechanism for developers to specify parameters, e.g. such as -c <country_code>, within the Xcode environment.

**Comment by twelve17** [comment]
I'm not sure what parameter this refers to. Can you elaborate?

**Comment by EMakadiya** [comment]
cant't find openalpr.framework while executing "bundle exec ./bin/build_frameworks.rb".
please help me how to get this framework?

**Comment by xcodewarrier** [comment]
In the sample code this is here, thanks, closing this out.

        delegate = new alpr::Alpr(
                                  [@"eu" UTF8String],
                                  [[[NSBundle mainBundle] pathForResource:@"openalpr.conf" ofType:nil] UTF8String],
                                  [[[NSBundle mainBundle] pathForResource:@"runtime_data" ofType:nil] UTF8String]
                                  );
