### ISSUE TITLE
Recognition not working with iPhone Camera output

### ISSUE THREAD

**Issue by xcodewarrier** [twelve17/openalpr-ios#15]
Hello,

I've managed to get the library working within my app when passing a static image as per the example, but when using an image from the camera recognition is unsuccessful every time - is there something differnent with the image thats returned from a AVCaptureSession()  Here's the code I'm using to get the image:

    NSData* imageData = [AVCaptureStillImageOutput jpegStillImageNSDataRepresentation:sampleBuffer];
    UIImage* image = [UIImage imageWithData:imageData];
    cv::Mat cvImage = [self cvMatFromUIImage:image];
    [self.plateScanner scanImage:cvImage onSuccess:^(NSArray * results) {

// Never suceeds

**Comment by twelve17** [comment]
The image data is probably different than what I am using.  I'm afraid this is outside the scope of this project.

**Comment by nicpro85** [comment]
image orientation
