### ISSUE TITLE
Executing bundle exec ./bin/build_frameworks.rb Syntax Errors

### ISSUE THREAD

**Issue by appslimited** [twelve17/openalpr-ios#16]
Hi I'm getting sytax errors when trying to run bundle exec ./bin/build_frameworks.rb

Any ideas?

Example:
lib/alpr/package/alpr.rb:31: syntax error, unexpected ',' (SyntaxError)
    def initialize(log_file:, logger:,

**Comment by twelve17** [comment]
Hi, check your ruby version and compare to the required version in the readme.

**Comment by twelve17** [comment]
No response from OP
