### ISSUE TITLE
iOS 8 Support

### ISSUE THREAD

**Issue by Skelzor** [twelve17/openalpr-ios#19]
I have issues running openALPR on iOS 8. The image-recognition process starts but never finishes. The whole framework is build for iOS 9, including the Tesseract-Framework. But the iOS-Version of Tesseract [here](https://github.com/gali8/Tesseract-OCR-iOS/wiki/Installation) is build for iOS 7. 

As far as I dive in, I can't understand the problems with the iOS Versions, because the Frameworks are written in C and don't use plattform-specific features - so I have no entry point to find the bug. Has someone a hint for me where the problem in the image-recognition process could be?

**Comment by twelve17** [comment]
@Skelzor This script does not use the tesseract code from the "Tesseract-OCR-iOS" project, it uses the original tesseract sources and builds for iOS 9.  I'm not sure how to debug your issue.  There may be something printed in the debug console, perhaps?

**Comment by twelve17** [comment]
No response from OP in a while.  Closing issue.

**Comment by GulinSS** [comment]
Same issue. Can't even understand why it is not working at <9.0
