### ISSUE TITLE
Problem to build 

### ISSUE THREAD

**Issue by zhouhao27** [twelve17/openalpr-ios#35]
When I run:

> bundle exec ./bin/build_frameworks.rb

I got the following error:

> configure: error: in `/Users/zhouhao/Projects/openalpr-ios/work/leptonica-1.71':
> configure: error: cannot run C compiled programs.
> If you meant to cross compile, use `--host'.
> See `config.log' for more details
> /Users/zhouhao/Projects/openalpr-ios/lib/alpr/utils.rb:44:in `execute': Child returned: pid 11788 exit 1 (RuntimeError)
> 	from /Users/zhouhao/Projects/openalpr-ios/lib/alpr/utils.rb:74:in `log_execute'
> 	from /Users/zhouhao/Projects/openalpr-ios/lib/alpr/package/automake.rb:147:in `do_autoconf_build'
> 	from /Users/zhouhao/Projects/openalpr-ios/lib/alpr/package/automake.rb:58:in `build_arch'
> 	from /Users/zhouhao/Projects/openalpr-ios/lib/alpr/package/base.rb:53:in `block in install'
> 	from /Users/zhouhao/Projects/openalpr-ios/lib/alpr/package/base.rb:52:in `each'
> 	from /Users/zhouhao/Projects/openalpr-ios/lib/alpr/package/base.rb:52:in `install'
> 	from ./bin/build_frameworks.rb:69:in `<main>'

Any idea? Thanks

**Comment by bluecaleb** [comment]
I'm having the same issue... Any chance you have found out a solution by now?

**Comment by bluecaleb** [comment]
Found a solution that worked for me. Details here:  https://github.com/twelve17/openalpr-ios/issues/30#issuecomment-261887794

**Comment by zhouhao27** [comment]
@bluecaleb nothing in the link.

**Comment by bluecaleb** [comment]
Hmmm, the link works for me... Here is a dump of my address bar: 
`https://github.com/twelve17/openalpr-ios/issues/30#issuecomment-261887794`

**Comment by zhouhao27** [comment]
At last I used the library built for React-native. It's working fine.
