### ISSUE TITLE
Cannot build leptonica for armv7

### ISSUE THREAD

**Issue by bknutzen** [twelve17/openalpr-ios#37]
Hello, 
i can build opencv, but it fails at leptonica. I attached the build.log and the leptonica config.log
files, maybe you can take a look at it? Any help would be appreciated. Below is the terminal output.

[build.log](https://github.com/twelve17/openalpr-ios/files/1820336/build.log)
[config.log](https://github.com/twelve17/openalpr-ios/files/1820337/config.log)

_:openalpr-ios knutzebj$ bundle exec bin/build_frameworks.rb
options: {}
Package opencv2 is already installed. Skipping build.
Downloading leptonica library.
Building leptonica for armv7 from /Users/knutzebj/openalpr-ios/work/leptonica-1.71
make: *** No rule to make target `clean'.  Stop.
make: *** No rule to make target `distclean'.  Stop.
configure: WARNING: if you wanted to set the --build type, don't use --host.
    If a cross compiler is detected then cross compile mode will be used
configure: WARNING: using cross tools not prefixed with host triplet
bundler: failed to load command: bin/build_frameworks.rb (bin/build_frameworks.rb)
RuntimeError: Child returned: pid 43450 exit 2
  /Users/knutzebj/openalpr-ios/lib/alpr/utils.rb:44:in `execute'
  /Users/knutzebj/openalpr-ios/lib/alpr/utils.rb:74:in `log_execute'
  /Users/knutzebj/openalpr-ios/lib/alpr/package/automake.rb:147:in `do_autoconf_build'
  /Users/knutzebj/openalpr-ios/lib/alpr/package/automake.rb:58:in `build_arch'
  /Users/knutzebj/openalpr-ios/lib/alpr/package/base.rb:53:in `block in install'
  /Users/knutzebj/openalpr-ios/lib/alpr/package/base.rb:52:in `each'
  /Users/knutzebj/openalpr-ios/lib/alpr/package/base.rb:52:in `install'
  bin/build_frameworks.rb:70:in `<top (required)>'

**Comment by snamrata007** [comment]
What is the answer for that?
